version: "3"

services:

  db:
    image: postgres
    container_name: postgres-db
    environment:
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    networks:
      - todo-network

  web:
    image: todo-app:0.0.1
    container_name: todo-app-container
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - todo-network

networks:
  todo-network: